In [17]:
import numpy as np
import matplotlib.pyplot as plt
from nnfs.datasets import spiral_data

In [16]:
class DenseLayer:
    def __init__(self, inputs, neurons):
        self.weights = 0.01 * np.random.randn(inputs, neurons)
        self.biases = np.zeros(neurons)
        
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights)
        

class ReluActivation:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
        
X,y = spiral_data(samples=10, classes=2)

dense = DenseLayer(2,3)
relu = ReluActivation()

dense.forward(X)
print(dense.output)

relu.forward(dense.output)
print(relu.output)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.29492021e-03  4.90500031e-04  5.25418651e-04]
 [ 3.22723240e-03  1.09349577e-03 -9.29102124e-04]
 [-1.90558519e-03  3.59558375e-05 -2.26749433e-03]
 [-8.73713873e-03 -2.59917682e-03  1.02285296e-03]
 [-1.04359003e-02 -3.17155977e-03  1.49863412e-03]
 [ 1.16580360e-02  2.21692639e-03  3.80431760e-03]
 [ 1.79770080e-02  4.24070787e-03  2.46973707e-03]
 [ 6.94509644e-03  3.08835910e-03 -5.03655394e-03]
 [-2.22100438e-02 -5.02802177e-03 -3.92401592e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.62525104e-03 -6.42468555e-04 -2.64891644e-04]
 [-4.52643629e-03 -1.32278129e-03  4.31703037e-04]
 [ 6.89261894e-03  1.47440902e-03  1.57297615e-03]
 [ 8.67653262e-03  2.58983492e-03 -1.05164970e-03]
 [ 1.73847003e-03  1.31624313e-03 -3.50481524e-03]
 [-9.87512232e-03 -1.65630448e-03 -4.13793481e-03]
 [-1.76707644e-02 -4.08806258e-03 -2.75984427e-03]
 [-9.42213854e-03 -3.64232017e-03  4.57080524e-03]
 [ 2.33814477e-02  5.60568700e-

In [25]:
class LayerDense:
    def __init__(self, inputs, neurons):
        self.weights = 0.01 * np.random.randn(inputs, neurons)
        self.biases = np.zeros(neurons)
        
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        
class Relu:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
        
class Softmax:
    def forward(self, inputs):
        exp = np.exp(inputs - np.max(inputs, axis = 1, keepdims = True))
        probs = exp / np.sum(exp, axis = 1, keepdims = True)
        self.output = probs
        
X,y = spiral_data(samples=10, classes=3)
dense = LayerDense(2,3)
dense.forward(X)
print("After Dense Layer forward pass: \n", dense.output, "\n")
activation = Relu()
activation.forward(dense.output)
print("After Relu activation: \n", activation.output, "\n")
output = Softmax()
output.forward(activation.output)
print("After Softmax activation: \n", output.output, "\n")

After Dense Layer forward pass: 
 [[ 0.          0.          0.        ]
 [ 0.00082682  0.00021483  0.00024916]
 [-0.00340256 -0.00376422  0.00140004]
 [-0.00289006 -0.00119987 -0.00049285]
 [ 0.00334626  0.00629187 -0.0035579 ]
 [ 0.00849454  0.00946884 -0.00355538]
 [ 0.00737572  0.00472897 -0.00014583]
 [-0.00895528 -0.01321021  0.00646638]
 [-0.01216394 -0.01029762  0.00234465]
 [ 0.00544059  0.01235129 -0.00757125]
 [ 0.          0.          0.        ]
 [ 0.0011353   0.00179779 -0.00092341]
 [ 0.00164082  0.00311929 -0.00177332]
 [ 0.00228785  0.00039122  0.00086058]
 [-0.00304172 -0.0060372   0.00350185]
 [-0.00850142 -0.00943719  0.00352514]
 [ 0.00623135  0.01037966 -0.0054996 ]
 [ 0.01061813  0.01389531 -0.00617838]
 [ 0.01109382  0.00834721 -0.00125881]
 [ 0.00025265 -0.00667417  0.00575182]
 [ 0.          0.          0.        ]
 [-0.00010794 -0.00088652  0.0006904 ]
 [-0.00321774 -0.00295208  0.00081227]
 [ 0.00420697  0.00584503 -0.00273391]
 [ 0.00681973  0.00737035 -0.0