In [3]:
# a single neuron with 3 inputs and related weights + bias
inputs = [1,2,3]
weights = [0.2,0.8,-0.5]
bias = 2
result = (inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias)
print(result)

2.3


In [4]:
# a single neuron with 4 inputs and related weights + bias
inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1.0]
# note that you need to have a weight for each input!
bias = 2
result = (inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias)
print(result)

4.8


In [5]:
# now we add two more neurons to our layer
# they all take the same inputs, but the weights and bias varies (this is what makes the outputs vary)
inputs = [1,2,3,2.5]

weights1 = [0.2,0.8,-0.5,1.0]
bias1 = 2
weights2 = [0.5, -0.91, 0.26, -0.5]
bias2 = 3
weights3 = [-0.26, -0.27, 0.17, 0.87]
bias3 = 0.5

outputs = [
    (inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1),
    (inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2),
    (inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3)
]

print(outputs)

#Each neuron is “connected” to the same inputs. 
#The difference is in the separate weights and bias that each neuron applies to the input. 
#This is called a fully connected neural network — 
# every neuron in the current layer has connections to every neuron from the previous layer.

[4.8, 1.21, 2.385]


In [28]:
# it gets impracticle to keep manually referencing 
# loop it:
inputs = [1,2,3,2.5]
weights = [
    [0.2,0.8,-0.5,1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]   
]
biases = [2,3,0.5]

# for each pair of weights and bias, iterate through the inputs array and multiply the n value in inputs by the n value in weights
outputs = []

for weight_array, bias in zip(weights, biases):
    neuron_output = 0
    for n_input, weight in zip(inputs, weight_array):
        neuron_output += (n_input * weight)
    neuron_output += bias        
    outputs.append(neuron_output)

print(outputs)

[4.8, 1.21, 2.385]


In [1]:
# Vectors, Tensors, and Arrays
# A list of lists is homologous if each list along a dimension is identically long, 
# and this must be true for each dimension.
# A tensor object is an object that can be represented as an array

In [5]:
# Vector addition and dot product
# When multiplying vectors, you either perform a dot product or a cross product. 
# A cross product results in a vector while a dot product results in a scalar (a single value/number).

# A dot product of two vectors is a sum of products of consecutive vector elements. 
# Both vectors must be of the same size (have an equal number of elements).

# given two vectors, we can manually find the dot product of those vectors
a = [1, 2, 3]
b = [2, 3, 4]

dot = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
print(dot)

# now what happens when we think about our two arrays as `inputs` and `weights`?
# this makes it very clear that a dot product is exactly what we need when calculating the output of a neuron
inputs = [1, 2, 3]
weights = [2, 3, 4]

dot = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2]
print(dot)

# vector addition is a similarly simple exercise where the sum of the two vectors is calculated element by element:
print([a[0]+b[0], a[1]+b[1], a[2]+b[2]])

20
20
[3, 5, 7]


In [5]:
# A single Neuron with NumPy
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

outputs = np.dot(inputs, weights) + bias

print(outputs)

4.8


In [6]:
# A Layer of Neurons with NumPy

# we still start with the same number of inputs; remember that each input is fed into each neuron
inputs = [1.0, 2.0, 3.0, 2.5]

# now we create a matrix containing the weights required for multiple neurons
# so in this context, each nested list of the matrix represents the weights to distinguish the output for a separate neuron
weights = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

# remember we also need a bias for each neuron, so we set one for each
biases = [2.0, 3.0, 0.5]

layer_outputs_wo_biases = np.dot(weights, inputs)
print(f'Outputs without biases added: #{layer_outputs_wo_biases}')
# this process is basically equivalent to:
# manual = [np.dot(weights[0], inputs), np.dot(weights[1], inputs), np.dot(weights[2], inputs)]

layer_outputs =  layer_outputs_wo_biases + biases
print(f'Final outputs with biases: #{layer_outputs}')

# you would likely want to condense this into a single operation, as we can perform matrix addition simply
# layer_outputs = np.dot(inputs, weights) + biases

# This syntax involving the dot product of weights and inputs followed by the vector addition of bias 
# is the most commonly used way to represent this calculation of inputs·weights+bias.

# To explain the order of parameters we are passing into npdot(), 
# we should think of it as whatever comes first will decide the output shape.
# That is why we need to pass weights before inputs
# np.dot(inputs, weights) will raise an error : ValueError: shapes (4,) and (3,4) not aligned: 4 (dim 0) != 3 (dim 0)

Outputs without biases added: #[ 2.8   -1.79   1.885]
Final outputs with biases: #[4.8   1.21  2.385]


In [7]:
# a batch of data
# Neural networks most commonly receive input data for training in batches, whereas we have just used a single observation

# Each of these values is a feature observation datum, and together they form a feature set instance, 
# also called an observation, or most commonly, a sample.
# feature set instance => observation => a sample

# Why train with many samples?
# 1. Faster to train in parallel processing
# 2. Fitting or training in batches gives you a higher chance of making more meaningful changes to weights and biases.

In [8]:
# Matrix Product
#The matrix product is an operation in which we have 2 matrices, 
# and we are performing dot products of all combinations of rows from the first matrix and the columns of the 2nd matrix, 
# resulting in a matrix of those atomic dot products:

weights = [0.36, 0.17, 0.96, 0.12]
inputs = [0.77, 0.09, 0.12, 0.81]
np.dot(weights, inputs)

# When performing matrix multiplication the shapes have to follow a pattern:
# the second dimension of the shape of the first array ## shape(3,7) ##
# must match the first dimension of the shape of the second array ## shape(7, 5) ##

# shape(3,7)
first = [
    [1,2,3,4,5,6,7],
    [1.2,2.3,3.4,4.5,5.6,6.7,7],
    [10,11,12,13,14,15,16]
]
# shape(7,5)
second = [
    [0.01,0.0391,0.0682,0.0974,0.1265],
    [0.1556,0.1847,0.2138,0.2429,0.2721],
    [0.3012,0.3303,0.3594,0.3885,0.4176],
    [0.4468,0.4759,0.505,0.5341,0.5632],
    [0.5924,0.6215,0.6506,0.6797,0.7088],
    [0.7379,0.7671,0.7962,0.8253,0.8544],
    [0.8835,0.9126,0.9418,0.9709,1.0]
]

# The shape of the resulting array is always the first dimension of the left array and the second dimension of the right array
# shape(3, 5)
np.dot(first, second)

# testing
first = [
    [1,4],
    [2,5],
    [3,6]
]
second = [
    [2,5,7],
    [3,3,3]
]
# operation to matrix multiply with numpy
np.matmul(first,second)


array([[14, 17, 19],
       [19, 25, 29],
       [24, 33, 39]])

In [9]:
# Row and Column Vectors
# The matrix of weights needs to be transposed so that we can take the matrix product of the inputs and weights
inputs = [
    [1,2,3,4,5],
    [1,1,2,3,5],
    [2,4,6,8,10]
]
weights = [
    [0.1,0.2,0.3,0.4,0.15],
    [2,3,4,5,6],
    [0.95,0.86,0.46,0.91,0.34]
]
biases = [1,-2,0]
outputs = np.dot(inputs, np.array(weights).T) + biases
print(outputs)

[[  4.75  68.     9.39]
 [  3.85  56.     7.16]
 [  8.5  138.    18.78]]
