In [1]:
import numpy as np
import nnfs

In [3]:
inputs = [1,2,3]
inputs2 = [[1,1,1], [2,2,2], [0.5, 0.5, 0.5], [0.75, 0.75, 0.75]]
weights = [[1,1,1], [2,2,2], [0.5, 0.5, 0.5]]
biases = [1, 5, 10, 100]
outputs = []

for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0
    for weight, input_n in zip(neuron_weights, inputs):
        neuron_output += weight * input_n
    neuron_output += neuron_bias
    outputs.append(neuron_output)
        
# print(outputs)

print(np.dot(inputs, weights))
print(np.dot(inputs, biases))
print(np.dot(inputs, weights[0]))
print(np.dot(weights, inputs) + biases)
# print(np.dot(weights, R.inputs2))

[7, 17, 13.0]
[6.5 6.5 6.5]
41
6
[ 7. 17. 13.]


In [7]:
inputs = [1,2,3,4]
weights = [[1.1,1.5,1.75,2],[2,2.5,2.9,3],[0.1,0.2,0.5,0.9]]
biases = [0,0,5]
weights2 = [[2,3,4],[1,1,1],[10,10,10],[2.5,1.1,3]]
biases2 = [1,1,2,3]

layer_1_outputs = np.dot(inputs, np.array(weights).T) + biases
layer_2_outputs = np.dot(layer_1_outputs, np.array(weights2).T) + biases2

print(layer_1_outputs)
print(layer_2_outputs)

[17.35 27.7  10.6 ]
[161.2    56.65  558.5   108.645]


In [13]:
a = [1,2,3]
b = [2,3,4]
print(np.dot(a, b))
np.dot(a, np.array(b).T)

20


20